export const questionsData = [
  {
    questions: [
      {
        number: 1,
        text: "Ini soal 1?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 2,
        text: "Mengapa sanksi seperti tilang sering kali tidak efektif dalam mengurangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 3,
        text: "Apa dampak parkir liar terhadap ruang publik?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 4,
        text: "Bagaimana cara mengurangi parkir liar di kawasan perkotaan?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 5,
        text: "Apa yang dapat dilakukan untuk meningkatkan kesadaran pengendara tentang parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 6,
        text: "Apa tujuan utama dari penegakan hukum yang tegas terhadap parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 7,
        text: "Apa dampak dari parkir liar terhadap lalu lintas?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 8,
        text: "Bagaimana teknologi dapat membantu menertibkan parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 9,
        text: "Mengapa penting untuk menyediakan tempat parkir yang memadai?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 10,
        text: "Bagaimana cara menegakkan aturan parkir di jalan raya?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 11,
        text: "Apa yang menyebabkan parkir liar di area perumahan?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 12,
        text: "Apa yang harus dilakukan oleh pemerintah untuk mengatasi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 13,
        text: "Bagaimana meningkatkan fasilitas transportasi umum dapat mengurangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 14,
        text: "Apa yang dimaksud dengan penegakan hukum yang tegas?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 15,
        text: "Apa yang dapat dilakukan masyarakat untuk membantu mengurangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 16,
        text: "Bagaimana peran media dalam menanggulangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 17,
        text: "Apa hubungan antara kebijakan transportasi publik dan parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 18,
        text: "Bagaimana penggunaan kendaraan pribadi berhubungan dengan parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 19,
        text: "Apa manfaat dari menyediakan lebih banyak ruang parkir?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 20,
        text: "Bagaimana cara mengurangi kemacetan akibat parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 21,
        text: "Mengapa pengendara sering mengabaikan aturan parkir?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 22,
        text: "Bagaimana penegakan hukum yang tegas dapat mengurangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 23,
        text: "Apa yang dimaksud dengan parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 24,
        text: "Apa yang perlu dilakukan pemerintah untuk mengatasi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 25,
        text: "Bagaimana cara terbaik untuk menanggulangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 26,
        text: "Apa dampak dari parkir liar terhadap kualitas hidup masyarakat?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 27,
        text: "Apa yang perlu dilakukan untuk menertibkan parkir liar di jalan raya?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 28,
        text: "Bagaimana sistem transportasi umum dapat membantu mengurangi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 29,
        text: "Apa yang dimaksud dengan transportasi ramah lingkungan?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
      {
        number: 30,
        text: "Bagaimana pengurangan kendaraan pribadi dapat mempengaruhi parkir liar?",
        options: [
          { value: "a", text: "Memudahkan akses ke jalan raya." },
          { value: "b", text: "Mengurangi jumlah kendaraan di jalan." },
          { value: "c", text: "Membahayakan karena berjalan di jalan raya." },
          { value: "d", text: "Membuat pejalan kaki lebih disiplin." },
          { value: "e", text: "Menambah ruang publik bagi pejalan kaki." },
        ],
      },
    ],
  },
];
