export const questionsData = [
  {
    questions: [
      {
        number: 1,
        text: "Hewan apa yang memiliki ciri-ciri seram?",
        options: [
          { value: "a", text: "Hiu." },
          { value: "b", text: "Ular" },
          { value: "c", text: "Buaya." },
          { value: "d", text: "Anjing." },
          { value: "e", text: "Cheetah." },
        ],
      },
      {
        number: 2,
        text: "Hewan apa yang memiliki cakar?",
        options: [
          { value: "a", text: "Kera." },
          { value: "b", text: "Anjing." },
          { value: "c", text: "Landak." },
          { value: "d", text: "Kukang." },
          { value: "e", text: "Cheetah." },
        ],
      },
      {
        number: 3,
        text: "Apa ciri-ciri dari kukang?",
        options: [
          { value: "a", text: "Gigi." },
          { value: "b", text: "Malas." },
          { value: "c", text: "Pelan." },
          { value: "d", text: "Tangan." },
          { value: "e", text: "Lambat." },
        ],
      },
      {
        number: 4,
        text: "Hewan apa yang memiliki ciri-ciri lembab?",
        options: [
          { value: "a", text: "Hiu." },
          { value: "b", text: "Ular." },
          { value: "c", text: "Katak." },
          { value: "d", text: "Buaya." },
          { value: "e", text: "Kura-kura." },
        ],
      },
      {
        number: 5,
        text: "Hewan apa yang memiliki sisik?",
        options: [
          { value: "a", text: "Capung." },
          { value: "b", text: "Buaya." },
          { value: "c", text: "Semut." },
          { value: "d", text: "Katak." },
          { value: "e", text: "Ikan." },
        ],
      },
      {
        number: 6,
        text: "Apa ciri-ciri dari kera?",
        options: [
          { value: "a", text: "Loyal." },
          { value: "b", text: "Rakus." },
          { value: "c", text: "Mulut." },
          { value: "d", text: "Telinga." },
          { value: "e", text: "Lucu." },
        ],
      },
      {
        number: 7,
        text: "Hewan apa yang memiliki ciri-ciri manja?",
        options: [
          { value: "a", text: "Nyamuk." },
          { value: "b", text: "Kukang." },
          { value: "c", text: "Kera." },
          { value: "d", text: "Anjing." },
          { value: "e", text: "Kucing." },
        ],
      },
      {
        number: 8,
        text: "Hewan apa yang memiliki sayap?",
        options: [
          { value: "a", text: "Tawon." },
          { value: "b", text: "Capung." },
          { value: "c", text: "Nyamuk." },
          { value: "d", text: "Kelelawar." },
          { value: "e", text: "Kupu-kupu." },
        ],
      },
      {
        number: 9,
        text: "Mengapa penting untuk menyediakan tempat parkir yang memadai?",
        options: [
          { value: "a", text: "Lembab." },
          { value: "b", text: "Lincah." },
          { value: "c", text: "Rakus." },
          { value: "d", text: "Gesit." },
          { value: "e", text: "Licik." },
        ],
      },
      {
        number: 10,
        text: "Hewan apa yang memiliki ciri-ciri rakus?",
        options: [
          { value: "a", text: "Hiu." },
          { value: "b", text: "Buaya." },
          { value: "c", text: "Anjing." },
          { value: "d", text: "Nyamuk." },
          { value: "e", text: "Cheetah." },
        ],
      },
      {
        number: 11,
        text: "Hewan apa yang memiliki gigi?",
        options: [
          { value: "a", text: "Orangutan." },
          { value: "b", text: "Anjing." },
          { value: "c", text: "Kera." },
          { value: "d", text: "Singa." },
          { value: "e", text: "Ular." },
        ],
      },
      {
        number: 12,
        text: "Apa ciri-ciri dari cheetah?",
        options: [
          { value: "a", text: "Lincah." },
          { value: "b", text: "Cepat." },
          { value: "c", text: "Akurat." },
          { value: "d", text: "Gesit." },
          { value: "e", text: "Gigi." },
        ],
      },
      {
        number: 13,
        text: "Hewan apa yang memiliki ciri-ciri lincah?",
        options: [
          { value: "a", text: "Ular." },
          { value: "b", text: "Kucing." },
          { value: "c", text: "Capung." },
          { value: "d", text: "Cheetah." },
          { value: "e", text: "Nyamuk." },
        ],
      },
      {
        number: 14,
        text: "Hewan apa yang memiliki telinga?",
        options: [
          { value: "a", text: "Elang." },
          { value: "b", text: "Gajah." },
          { value: "c", text: "Kucing." },
          { value: "d", text: "Anjing." },
          { value: "e", text: "Kukang." },
        ],
      },
      {
        number: 15,
        text: "Apa ciri-ciri dari hiu?",
        options: [
          { value: "a", text: "Sisik." },
          { value: "b", text: "Sirip." },
          { value: "c", text: "Taring." },
          { value: "d", text: "Insang." },
          { value: "e", text: "Ganas." },
        ],
      },
      {
        number: 16,
        text: "Hewan apa yang memiliki ciri-ciri ganas?",
        options: [
          { value: "a", text: "Cheetah." },
          { value: "b", text: "Kucing." },
          { value: "c", text: "Anjing." },
          { value: "d", text: "Buaya." },
          { value: "e", text: "Elang." },
        ],
      },
      {
        number: 17,
        text: "Hewan apa yang memiliki cakar?",
        options: [
          { value: "a", text: "Kucing." },
          { value: "b", text: "Anjing." },
          { value: "c", text: "Harimau." },
          { value: "d", text: "Cheetah." },
          { value: "e", text: "Serigala." },
        ],
      },
      {
        number: 18,
        text: "Apa ciri-ciri dari nyamuk?",
        options: [
          { value: "a", text: "Berisik." },
          { value: "b", text: "Darah." },
          { value: "c", text: "Rakus." },
          { value: "d", text: "Sungut." },
          { value: "e", text: "Antena." },
        ],
      },
      {
        number: 19,
        text: "Hewan apa yang memiliki ciri-ciri akurat?",
        options: [
          { value: "a", text: "Kera." },
          { value: "b", text: "Semut." },
          { value: "c", text: "Elang." },
          { value: "d", text: "Katak." },
          { value: "e", text: "Gajah." },
        ],
      },
      {
        number: 20,
        text: "Hewan apa yang memiliki antena?",
        options: [
          { value: "a", text: "Kupu-kupu." },
          { value: "b", text: "Capung." },
          { value: "c", text: "Nyamuk." },
          { value: "d", text: "Semut." },
          { value: "e", text: "Rusa." },
        ],
      },
      {
        number: 21,
        text: "Apa ciri-ciri dari anjing?",
        options: [
          { value: "a", text: "Cerdas." },
          { value: "b", text: "Manja." },
          { value: "c", text: "Cakar." },
          { value: "d", text: "Mulut." },
          { value: "e", text: "Gigi." },
        ],
      },
      {
        number: 22,
        text: "Hewan apa yang memiliki ciri-ciri cerdas?",
        options: [
          { value: "a", text: "Gajah." },
          { value: "b", text: "Elang." },
          { value: "c", text: "Semut." },
          { value: "d", text: "Kera." },
          { value: "e", text: "Ular." },
        ],
      },
      {
        number: 23,
        text: "Hewan apa yang memiliki sisik?",
        options: [
          { value: "a", text: "Ular." },
          { value: "b", text: "Lalat." },
          { value: "c", text: "Udang." },
          { value: "d", text: "Iguana." },
          { value: "e", text: "Bunglon." },
        ],
      },
      {
        number: 24,
        text: "Apa ciri-ciri dari landak?",
        options: [
          { value: "a", text: "Sisik." },
          { value: "b", text: "Duri." },
          { value: "c", text: "Luka." },
          { value: "d", text: "Lancip." },
          { value: "e", text: "Taring." },
        ],
      },
      {
        number: 25,
        text: "Hewan apa yang memiliki ciri-ciri lucu?",
        options: [
          { value: "a", text: "Hiu." },
          { value: "b", text: "Kera." },
          { value: "c", text: "Anjing." },
          { value: "d", text: "Gajah." },
          { value: "e", text: "Kucing." },
        ],
      },
      {
        number: 26,
        text: "Hewan apa yang memiliki lidah?",
        options: [
          { value: "a", text: "Bunglon." },
          { value: "b", text: "Kucing." },
          { value: "c", text: "Katak." },
          { value: "d", text: "Kera." },
          { value: "e", text: "Paus." },
        ],
      },
      {
        number: 27,
        text: "Apa ciri-ciri dari capung?",
        options: [
          { value: "a", text: "Gesit." },
          { value: "b", text: "Antena." },
          { value: "c", text: "Sayap." },
          { value: "d", text: "Cerdas." },
          { value: "e", text: "Tajam." },
        ],
      },
      {
        number: 28,
        text: "Hewan apa yang memiliki ciri-ciri kokoh?",
        options: [
          { value: "a", text: "Gajah." },
          { value: "b", text: "Buaya." },
          { value: "c", text: "Semut." },
          { value: "d", text: "Landak." },
          { value: "e", text: "Kukang." },
        ],
      },
      {
        number: 29,
        text: "Hewan apa yang memiliki gigi?",
        options: [
          { value: "a", text: "Hiu." },
          { value: "b", text: "Macan." },
          { value: "c", text: "Buaya." },
          { value: "d", text: "Cheetah." },
          { value: "e", text: "Harimau." },
        ],
      },
      {
        number: 30,
        text: "Apa ciri-ciri dari katak?",
        options: [
          { value: "a", text: "Mulut." },
          { value: "b", text: "Lendir." },
          { value: "c", text: "Lembab." },
          { value: "d", text: "Lengket." },
          { value: "e", text: "Basah." },
        ],
      },
    ],
  },
];
