export const questionsData = [
  {
    questions: [
      {
        number: 1,
        text: "Seorang peternak memiliki 400 liter susu segar untuk dijual kepada pelanggan. Di akhir hari masih tersisa 150 liter susu yang belum terjual. Berapa literkah banyaknya susu yang berhasil dijual kepada pelanggan?",
        options: [
          { value: "a", text: "200" },
          { value: "b", text: "250" },
          { value: "c", text: "300" },
          { value: "d", text: "350" },
          { value: "e", text: "400" },
        ],
      },
      {
        number: 2,
        text: "Sebanyak 45 karung berisi beras massanya adalah 1.620 kg. Setiap karung kosong beratnya 9 kg. Berapakah massa seluruh beras tersebut?",
        options: [
          { value: "a", text: "1.275 kg" },
          { value: "b", text: "1.260 kg" },
          { value: "c", text: "1.245 kg" },
          { value: "d", text: "1.230 kg" },
          { value: "e", text: "1.215 kg" },
        ],
      },
      {
        number: 3,
        text: "Seorang petani memiliki 20 tangki air, masing-masing tangki berisi penuh air dengan berat total 800 ton. Jika berat setiap tangki kosong adalah 2 ton, berapa tonkah berat air dalam semua tangki tersebut?",
        options: [
          { value: "a", text: "760" },
          { value: "b", text: "770" },
          { value: "c", text: "780" },
          { value: "d", text: "790" },
          { value: "e", text: "800" },
        ],
      },
      {
        number: 4,
        text: "Seorang petani memanen 340 buah apel setiap harinya. Jika setiap kotak dapat menampung 25 buah apel, berapa buah apel yang tersisa dan tidak dikemas dalam kotak?",
        options: [
          { value: "a", text: "10" },
          { value: "b", text: "15" },
          { value: "c", text: "20" },
          { value: "d", text: "23" },
          { value: "e", text: "25" },
        ],
      },
      {
        number: 5,
        text: "Sebanyak 40 ember yang berisi air beratnya 250 kg. Setiap ember kosong beratnya 1 kg. Berapakah berat seluruh air tersebut?",
        options: [
          { value: "a", text: "250 kg" },
          { value: "b", text: "245 kg" },
          { value: "c", text: "240 kg" },
          { value: "d", text: "210 kg" },
          { value: "e", text: "200 kg" },
        ],
      },
      {
        number: 6,
        text: "Sebuah acara pesta dapat dipersiapkan oleh 9 panitia dalam waktu 6 jam. Berapa orang panitia yang dibutuhkan untuk mempersiapkan acara dalam waktu 1 jam?",
        options: [
          { value: "a", text: "27" },
          { value: "b", text: "36" },
          { value: "c", text: "45" },
          { value: "d", text: "54" },
          { value: "e", text: "63" },
        ],
      },
      {
        number: 7,
        text: "Sebuah mesin pencuci piring menghabiskan 14 liter air untuk mencuci 35 piring. Berapa liter air yang dihabiskan untuk mencuci 10 piring?",
        options: [
          { value: "a", text: "2" },
          { value: "b", text: "3" },
          { value: "c", text: "4" },
          { value: "d", text: "6" },
          { value: "e", text: "7" },
        ],
      },
      {
        number: 8,
        text: "Seorang pelaut berada 15 km di sebelah utara sebuah pelabuhan dan 7 km di sebelah selatan pulau. Berapa kilometerkah jarak antara pelabuhan dengan pulau?",
        options: [
          { value: "a", text: "7" },
          { value: "b", text: "15" },
          { value: "c", text: "20" },
          { value: "d", text: "22" },
          { value: "e", text: "28" },
        ],
      },
      {
        number: 9,
        text: "Jika harga satu liter cat yang dapat menutupi 12,5 m² adalah Rp80.000,-, berapa rupiahkah harga cat untuk menutupi 25 m²?",
        options: [
          { value: "a", text: "Rp200.000,-" },
          { value: "b", text: "Rp160.000,-" },
          { value: "c", text: "Rp150.000,-" },
          { value: "d", text: "Rp120.000,-" },
          { value: "e", text: "Rp100.000,-" },
        ],
      },
      {
        number: 10,
        text: "Seorang pembuat kue memiliki persediaan tepung yang cukup untuk membuat 20 kue selama 15 hari. Dengan jumlah tepung yang sama, berapa harikah persediaan tersebut cukup jika jumlah kue yang dibuat adalah 60 kue?",
        options: [
          { value: "a", text: "3" },
          { value: "b", text: "5" },
          { value: "c", text: "7" },
          { value: "d", text: "10" },
          { value: "e", text: "15" },
        ],
      },
      {
        number: 11,
        text: "Seorang koki ingin membuat jus yang terdiri dari satu bagian air, dua bagian buah, dan tiga bagian es batu. Jika koki ingin membuat jus dengan total berat 36 kg, berapa kg es batu yang dibutuhkan?",
        options: [
          { value: "a", text: "6" },
          { value: "b", text: "12" },
          { value: "c", text: "15" },
          { value: "d", text: "18" },
          { value: "e", text: "21" },
        ],
      },
      {
        number: 12,
        text: "Total jumlah buku di dua rak perpustakaan adalah 784 buku. Rak pertama memiliki 136 buku lebih banyak daripada rak kedua. Berapa banyak buku yang terdapat di rak pertama?",
        options: [
          { value: "a", text: "460" },
          { value: "b", text: "460" },
          { value: "c", text: "410" },
          { value: "d", text: "360" },
          { value: "e", text: "324" },
        ],
      },
      {
        number: 13,
        text: "Sebuah toko menjual barang dengan harga Rp50.000,-. Barang tersebut dibeli dengan diskon 20% dan dijual kembali dengan harga Rp45.000,-. Berapa keuntungan yang diperoleh?",
        options: [
          { value: "a", text: "Rp10.000,-" },
          { value: "b", text: "Rp9.000,-" },
          { value: "c", text: "Rp8.000,-" },
          { value: "d", text: "Rp7.000,-" },
          { value: "e", text: "Rp5.000,-" },
        ],
      },
      {
        number: 14,
        text: "Di sebuah klub olahraga terdapat 20 anggota. Jika terdapat 5 orang yang menyukai berenang dan bersepeda, 7 orang hanya menyukai bersepeda, dan 4 orang tidak menyukai keduanya. Berapa orangkah yang hanya menyukai berenang?",
        options: [
          { value: "a", text: "3" },
          { value: "b", text: "4" },
          { value: "c", text: "5" },
          { value: "d", text: "7" },
          { value: "e", text: "9" },
        ],
      },
      {
        number: 15,
        text: "Sebuah mesin pengisi botol dapat mengisi 24 botol dalam waktu 1 jam 30 menit. Berapa banyak botol yang dapat diisi dalam waktu 45 menit?",
        options: [
          { value: "a", text: "6" },
          { value: "b", text: "8" },
          { value: "c", text: "10" },
          { value: "d", text: "12" },
          { value: "e", text: "15" },
        ],
      },
      {
        number: 16,
        text: "Sebuah mesin cetak dapat mencetak 5.280 lembar kertas dalam waktu 6 jam. Berapa lembar kertas yang dapat dicetak dalam waktu 30 menit?",
        options: [
          { value: "a", text: "400" },
          { value: "b", text: "420" },
          { value: "c", text: "440" },
          { value: "d", text: "460" },
          { value: "e", text: "480" },
        ],
      },
      {
        number: 17,
        text: "Sebuah proyek pengecatan dapat diselesaikan dalam waktu 3 jam 20 menit oleh 6 orang. Berapa jumlah orang yang harus ditambahkan agar proyek dapat selesai dalam waktu 1 jam 40 menit?",
        options: [
          { value: "a", text: "4" },
          { value: "b", text: "5" },
          { value: "c", text: "6" },
          { value: "d", text: "7" },
          { value: "e", text: "8" },
        ],
      },
      {
        number: 18,
        text: "Jika seseorang mengendarai mobil sejauh 120 km dengan kecepatan 60 km/jam, lalu melanjutkan perjalanan sejauh 180 km dengan kecepatan 90 km/jam, berapa total waktu yang dibutuhkan?",
        options: [
          { value: "a", text: "3,5 jam" },
          { value: "b", text: "4 jam" },
          { value: "c", text: "4,5 jam" },
          { value: "d", text: "5 jam" },
          { value: "e", text: "5,5 jam" },
        ],
      },
      {
        number: 19,
        text: "Sebuah kolam renang yang luasnya 450 meter persegi dibagi menjadi dua bagian. Satu bagian memiliki luas 1/4 dari bagian lainnya. Berapakah dalam m² luas bagian terkecil?",
        options: [
          { value: "a", text: "90" },
          { value: "b", text: "100" },
          { value: "c", text: "110" },
          { value: "d", text: "112" },
          { value: "e", text: "120" },
        ],
      },
      {
        number: 20,
        text: "Di sebuah bengkel, mesin X dapat memproduksi 36 suku cadang dalam satu jam, sedangkan mesin Y dapat memproduksi 20 suku cadang dalam satu jam. Berapa suku cadang yang diproduksi mesin Y, jika mesin X telah memproduksi 54 suku cadang?",
        options: [
          { value: "a", text: "24" },
          { value: "b", text: "28" },
          { value: "c", text: "30" },
          { value: "d", text: "32" },
          { value: "e", text: "36" },
        ],
      },
      {
        number: 21,
        text: "Seorang teknisi menggunakan 540 watt listrik untuk menjalankan mesin selama 15 jam. Berapa watt listrik yang digunakan untuk menjalankan mesin selama 7 jam?",
        options: [
          { value: "a", text: "240" },
          { value: "b", text: "252" },
          { value: "c", text: "264" },
          { value: "d", text: "276" },
          { value: "e", text: "288" },
        ],
      },
      {
        number: 22,
        text: "Seorang pedagang membeli barang seharga Rp200.000,- dengan diskon 15%, lalu menjual barang tersebut dengan keuntungan 25%. Berapakah harga jual barang tersebut?",
        options: [
          { value: "a", text: "Rp212.500,-" },
          { value: "b", text: "Rp218.750,-" },
          { value: "c", text: "Rp225.000,-" },
          { value: "d", text: "Rp230.000,-" },
          { value: "e", text: "Rp235.000,-" },
        ],
      },
      {
        number: 23,
        text: "Jika 5 kg gula dapat digunakan untuk membuat 20 kue kecil, berapa kg gula yang dibutuhkan untuk membuat 50 kue besar jika kue besar membutuhkan 10% lebih banyak gula?",
        options: [
          { value: "a", text: "17,5" },
          { value: "b", text: "16,25" },
          { value: "c", text: "15" },
          { value: "d", text: "14" },
          { value: "e", text: "13,75" },
        ],
      },
      {
        number: 24,
        text: "Sebuah perusahaan dengan 10 pekerja dapat memproduksi 100 barang dalam 5 jam. Karena peningkatan permintaan, perusahaan perlu memproduksi 800 barang dalam 24 jam. Namun, karena masalah teknis, perusahaan hanya dapat beroperasi selama 20 jam. Berapa banyak pekerja tambahan yang diperlukan untuk mencapai target produksi?",
        options: [
          { value: "a", text: "5" },
          { value: "b", text: "8" },
          { value: "c", text: "10" },
          { value: "d", text: "12" },
          { value: "e", text: "15" },
        ],
      },
      {
        number: 25,
        text: "Jika pekerja A dapat menyelesaikan pekerjaan dalam 4 jam dan pekerja B dalam 6 jam, berapa lama keduanya akan menyelesaikan pekerjaan tersebut jika mereka bekerja bersama?",
        options: [
          { value: "a", text: "1,6 jam" },
          { value: "b", text: "2 jam" },
          { value: "c", text: "2,4 jam" },
          { value: "d", text: "3 jam" },
          { value: "e", text: "3,6 jam" },
        ],
      },
      {
        number: 26,
        text: "Jika Anda mencampur 2 liter larutan gula dengan konsentrasi 20% dengan 3 liter larutan gula dengan konsentrasi 40%, berapa konsentrasi akhir larutan tersebut?",
        options: [
          { value: "a", text: "28%" },
          { value: "b", text: "30%" },
          { value: "c", text: "32%" },
          { value: "d", text: "34%" },
          { value: "e", text: "36%" },
        ],
      },
      {
        number: 27,
        text: "Jumlah total siswa di dua ruang kelas adalah 94 siswa. Ruang kelas yang besar menampung 10 siswa lebih banyak dibandingkan ruang kelas yang kecil. Berapa banyak siswa yang terdapat di ruang kelas yang besar?",
        options: [
          { value: "a", text: "42" },
          { value: "b", text: "47" },
          { value: "c", text: "50" },
          { value: "d", text: "52" },
          { value: "e", text: "57" },
        ],
      },
      {
        number: 28,
        text: "Tentukan nilai rata-rata dari data berikut: 3, 5, 5, 7, 9, 11, 11, 13",
        options: [
          { value: "a", text: "6" },
          { value: "b", text: "7" },
          { value: "c", text: "8" },
          { value: "d", text: "9" },
          { value: "e", text: "10" },
        ],
      },
      {
        number: 29,
        text: "Bapak A membeli makanan di restoran dengan harga Rp500.000,-, Ia harus membayar pajak restoran sebesar 12,5%. Berapa pajak yang harus dibayar Bapak A?",
        options: [
          { value: "a", text: "Rp50.000,-" },
          { value: "b", text: "Rp55.000,-" },
          { value: "c", text: "Rp60.000,-" },
          { value: "d", text: "Rp62.500,-" },
          { value: "e", text: "Rp65.000,-" },
        ],
      },
      {
        number: 30,
        text: "Dua kereta api bergerak dengan arah yang berlawanan dari stasiun yang berbeda. Kereta A melaju dengan kecepatan 50 km/jam dan Kereta B dengan kecepatan 70 km/jam. Jika jarak antar stasiun adalah 240 km, berapa lama waktu yang dibutuhkan kereta-kereta tersebut untuk bertemu?",
        options: [
          { value: "a", text: "1 jam" },
          { value: "b", text: "1,5 jam" },
          { value: "c", text: "2 jam" },
          { value: "d", text: "2,5 jam" },
          { value: "e", text: "3 jam" },
        ],
      },
    ],
  },
];
