export const questionsData = [
  {
    questions: [
      {
        number: 1,
        text: "Luruh = _____",
        options: [
          { value: "a", text: "Kokoh" },
          { value: "b", text: "Patah" },
          { value: "c", text: "Hancur" },
          { value: "d", text: "Lenyap" },
          { value: "e", text: "Gumpal" },
        ],
      },
      {
        number: 2,
        text: "Mutlak = _____",
        options: [
          { value: "a", text: "Sementara" },
          { value: "b", text: "Pasti" },
          { value: "c", text: "Parsial" },
          { value: "d", text: "Tentatif" },
          { value: "e", text: "Yakin" },
        ],
      },
      {
        number: 3,
        text: "Lenting = _____",
        options: [
          { value: "a", text: "Kaku" },
          { value: "b", text: "Elastis" },
          { value: "c", text: "Kendur" },
          { value: "d", text: "Lemas" },
          { value: "e", text: "Rapuh" },
        ],
      },
      {
        number: 4,
        text: "Respons = _____",
        options: [
          { value: "a", text: "Kritik" },
          { value: "b", text: "Serangan" },
          { value: "c", text: "Tanggapan" },
          { value: "d", text: "Saran" },
          { value: "e", text: "Laporan" },
        ],
      },
      {
        number: 5,
        text: "Tradisi = _____",
        options: [
          { value: "a", text: "Inovasi" },
          { value: "b", text: "Aksi" },
          { value: "c", text: "Penemuan" },
          { value: "d", text: "Kejadian" },
          { value: "e", text: "Kebiasaan" },
        ],
      },
      {
        number: 6,
        text: "Klaim = _____",
        options: [
          { value: "a", text: "Tuntutan" },
          { value: "b", text: "Permintaan" },
          { value: "c", text: "Hak" },
          { value: "d", text: "Gugatan" },
          { value: "e", text: "Bukti" },
        ],
      },
      {
        number: 7,
        text: "Meronce = _____",
        options: [
          { value: "a", text: "Membongkar" },
          { value: "b", text: "Menerobos" },
          { value: "c", text: "Menjahit" },
          { value: "d", text: "Membangun" },
          { value: "e", text: "Menyusun " },
        ],
      },
      {
        number: 8,
        text: "Sangkal = _____",
        options: [
          { value: "a", text: "Setuju" },
          { value: "b", text: "Mengira" },
          { value: "c", text: "Akui" },
          { value: "d", text: "Bantah" },
          { value: "e", text: "Yakini" },
        ],
      },
      {
        number: 9,
        text: "Arungi = _____",
        options: [
          { value: "a", text: "Hindari" },
          { value: "b", text: "Lewati" },
          { value: "c", text: "Jauhi" },
          { value: "d", text: "Singgahi" },
          { value: "e", text: "Berhenti" },
        ],
      },
      {
        number: 10,
        text: "Diplomasi = _____",
        options: [
          { value: "a", text: "Negosiasi" },
          { value: "b", text: "Permusuhan" },
          { value: "c", text: "Persetujuan" },
          { value: "d", text: "Perjanjian" },
          { value: "e", text: "Konflik" },
        ],
      },
      {
        number: 11,
        text: "Hierarki = _____",
        options: [
          { value: "a", text: "Struktur" },
          { value: "b", text: "Kesetaraan" },
          { value: "c", text: "Hubungan" },
          { value: "d", text: "Tingkatan" },
          { value: "e", text: "Pengurutan" },
        ],
      },
      {
        number: 12,
        text: "Birokrat = _____",
        options: [
          { value: "a", text: "Kekuasaan" },
          { value: "b", text: "Aparat" },
          { value: "c", text: "Proses" },
          { value: "d", text: "Sistem" },
          { value: "e", text: "Prosedur" },
        ],
      },
      {
        number: 13,
        text: "Legitimasi = _____",
        options: [
          { value: "a", text: "Bukti" },
          { value: "b", text: "Kesepakatan" },
          { value: "c", text: "Keabsahan" },
          { value: "d", text: "Legalitas" },
          { value: "e", text: "Formalitas" },
        ],
      },
      {
        number: 14,
        text: "Ergonomis = _____",
        options: [
          { value: "a", text: "Keteraturan" },
          { value: "b", text: "Kesederhanaan" },
          { value: "c", text: "Efisiensi" },
          { value: "d", text: "Ketepatan" },
          { value: "e", text: "Kenyamanan " },
        ],
      },
      {
        number: 15,
        text: "Paradoks = _____",
        options: [
          { value: "a", text: "Kontradiksi" },
          { value: "b", text: "Abstrak" },
          { value: "c", text: "Kesepakatan" },
          { value: "d", text: "Kemustahilan" },
          { value: "e", text: "Komplikasi" },
        ],
      },
      {
        number: 16,
        text: "Anomali = _____",
        options: [
          { value: "a", text: "Ketidakpastian" },
          { value: "b", text: "Keanehan" },
          { value: "c", text: "Keganjilan" },
          { value: "d", text: "Ketidaknormalan" },
          { value: "e", text: "Kekacauan" },
        ],
      },
      {
        number: 17,
        text: "Defisit = _____",
        options: [
          { value: "a", text: "Kekurangan" },
          { value: "b", text: "Kelimpahan" },
          { value: "c", text: "Kelebihan" },
          { value: "d", text: "Keterbatasan" },
          { value: "e", text: "Keseimbangan" },
        ],
      },
      {
        number: 18,
        text: "Ekshumasi = _____",
        options: [
          { value: "a", text: "Pemakaman" },
          { value: "b", text: "Penggalian" },
          { value: "c", text: "Pembakaran" },
          { value: "d", text: "Pemanusiaan" },
          { value: "e", text: "Pemindahan" },
        ],
      },
      {
        number: 19,
        text: "Abolisi = _____",
        options: [
          { value: "a", text: "Penghapusan" },
          { value: "b", text: "Pemindahan" },
          { value: "c", text: "Pembuangan" },
          { value: "d", text: "Penundaan" },
          { value: "e", text: "Penelantaran" },
        ],
      },
      {
        number: 20,
        text: "Sentralisasi = _____",
        options: [
          { value: "a", text: "Pengaturan" },
          { value: "b", text: "Pemusatan" },
          { value: "c", text: "Sistemn" },
          { value: "d", text: "Kekuasaan" },
          { value: "e", text: "Pemisahan " },
        ],
      },
      {
        number: 21,
        text: "Asimilasi = _____",
        options: [
          { value: "a", text: "Akulturasi" },
          { value: "b", text: "Pengusiran" },
          { value: "c", text: "Penyatuan" },
          { value: "d", text: "Asosiasi" },
          { value: "e", text: "Koalisi" },
        ],
      },
      {
        number: 22,
        text: "Analogi >< _____",
        options: [
          { value: "a", text: "Kesamaan" },
          { value: "b", text: "Hubungan" },
          { value: "c", text: "Keterkaitan" },
          { value: "d", text: "Perbedaan" },
          { value: "e", text: "Metafora" },
        ],
      },
      {
        number: 23,
        text: "Loyalitas >< _____",
        options: [
          { value: "a", text: "Kecurangan" },
          { value: "b", text: "Kesetiaan" },
          { value: "c", text: "Pengkhianatan" },
          { value: "d", text: "Pengabaian" },
          { value: "e", text: "Ketidakpedulian" },
        ],
      },
      {
        number: 24,
        text: "Eskalasi >< _____",
        options: [
          { value: "a", text: "Peningkatan" },
          { value: "b", text: "Penurunan" },
          { value: "c", text: "Pertumbuhan" },
          { value: "d", text: "Penyempitan" },
          { value: "e", text: "Lonjakan" },
        ],
      },
      {
        number: 25,
        text: "Eksplisit >< _____",
        options: [
          { value: "a", text: "Tersirat" },
          { value: "b", text: "Jelas" },
          { value: "c", text: "Nyata" },
          { value: "d", text: "Rinci" },
          { value: "e", text: "Transparan" },
        ],
      },
      {
        number: 26,
        text: "Objektif >< _____",
        options: [
          { value: "a", text: "Muslihat" },
          { value: "b", text: "Bias" },
          { value: "c", text: "Faktual" },
          { value: "d", text: "Akurat" },
          { value: "e", text: "Realistis" },
        ],
      },
      {
        number: 27,
        text: "Definitif >< _____",
        options: [
          { value: "a", text: "Tentatif" },
          { value: "b", text: "Fundamental" },
          { value: "c", text: "Absolut" },
          { value: "d", text: "Konklusif" },
          { value: "e", text: "Substansial" },
        ],
      },
      {
        number: 28,
        text: "Anyam >< _____.",
        options: [
          { value: "a", text: "Urai" },
          { value: "b", text: "Ikat" },
          { value: "c", text: "Rangkai" },
          { value: "d", text: "Sambung" },
          { value: "e", text: "Hancur" },
        ],
      },
      {
        number: 29,
        text: "Papah >< _____",
        options: [
          { value: "a", text: "Dorong" },
          { value: "b", text: "Lepas" },
          { value: "c", text: "Topang" },
          { value: "d", text: "Angkat" },
          { value: "e", text: "Ibu" },
        ],
      },
      {
        number: 30,
        text: "Luruh >< _____",
        options: [
          { value: "a", text: "Tahan" },
          { value: "b", text: "Hancur" },
          { value: "c", text: "Hilang" },
          { value: "d", text: "Muncul" },
          { value: "e", text: "Runtuh" },
        ],
      },
      {
        number: 31,
        text: "Sengketa >< _____",
        options: [
          { value: "a", text: "Konflik" },
          { value: "b", text: "Perbuatan" },
          { value: "c", text: "Permusuhan" },
          { value: "d", text: "Perbaikan" },
          { value: "e", text: "Kesepakatan " },
        ],
      },
      {
        number: 32,
        text: "Antitesis >< _____",
        options: [
          { value: "a", text: "Kesamaan" },
          { value: "b", text: "Hipotesis" },
          { value: "c", text: "Kontradiksi" },
          { value: "d", text: "Aliansi" },
          { value: "e", text: "Oposisi" },
        ],
      },
      {
        number: 33,
        text: "Nirwana >< _____",
        options: [
          { value: "a", text: "Harmoni" },
          { value: "b", text: "Surga" },
          { value: "c", text: "Realitas" },
          { value: "d", text: "Khayalan" },
          { value: "e", text: "Kesempurnaan" },
        ],
      },
      {
        number: 34,
        text: "Implikasi >< _____",
        options: [
          { value: "a", text: "Konsekuensi" },
          { value: "b", text: "Pengabaian" },
          { value: "c", text: "Keterlibatan" },
          { value: "d", text: "Komplikasi" },
          { value: "e", text: "Dampak" },
        ],
      },
      {
        number: 35,
        text: "Elusif >< _____",
        options: [
          { value: "a", text: "Rumit" },
          { value: "b", text: "Sederhana" },
          { value: "c", text: "Sulit" },
          { value: "d", text: "Kabur" },
          { value: "e", text: "Abstrak" },
        ],
      },
      {
        number: 36,
        text: "Nirmala >< _____",
        options: [
          { value: "a", text: "Tiada" },
          { value: "b", text: "Suci" },
          { value: "c", text: "Kotor" },
          { value: "d", text: "Sakit" },
          { value: "e", text: "Sehat" },
        ],
      },
      {
        number: 37,
        text: "Maladaptif >< _____",
        options: [
          { value: "a", text: "Sesuai" },
          { value: "b", text: "Efektif" },
          { value: "c", text: "Fleksibel" },
          { value: "d", text: "Terbuka" },
          { value: "e", text: "Responsif" },
        ],
      },
      {
        number: 38,
        text: "Kontemporer >< _____",
        options: [
          { value: "a", text: "Kuno" },
          { value: "b", text: "Modern" },
          { value: "c", text: "Terkini" },
          { value: "d", text: "Populer" },
          { value: "e", text: "kepastian" },
        ],
      },
      {
        number: 39,
        text: "Mitigasi >< _____",
        options: [
          { value: "a", text: "Pemberatan" },
          { value: "b", text: "Perburukan" },
          { value: "c", text: "Peringanan" },
          { value: "d", text: "Penanganan" },
          { value: "e", text: "Pencegahan" },
        ],
      },
      {
        number: 40,
        text: "Stagnasi >< _____",
        options: [
          { value: "a", text: "Pembaruan" },
          { value: "b", text: "Kemerosotan" },
          { value: "c", text: "Keberhasilan" },
          { value: "d", text: "Ketekunan" },
          { value: "e", text: "Perhentian" },
        ],
      },
      {
        number: 41,
        text: "Papah >< _____",
        options: [
          { value: "a", text: "Simpan" },
          { value: "b", text: "Publikasi" },
          { value: "c", text: "Sebar" },
          { value: "d", text: "Kirim" },
          { value: "e", text: "Unduh" },
        ],
      },
      {
        number: 42,
        text: "Luruh >< _____",
        options: [
          { value: "a", text: "Hapus" },
          { value: "b", text: "Letakkan" },
          { value: "c", text: "Tambahkan" },
          { value: "d", text: "Catut" },
          { value: "e", text: "Reduksi" },
        ],
      },
    ],
  },
];
