// Define questions with dynamic structure
export const imageData = [
  {
    number: 1,
    image: "/assets/soal-VZ/Soal 1.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/1. a.png" },
      { value: "b", image: "/assets/soal-VZ/1. b.png" },
      { value: "c", image: "/assets/soal-VZ/1. c.png" },
      { value: "d", image: "/assets/soal-VZ/1. d.png" },
      { value: "e", image: "/assets/soal-VZ/1. e.png" },
    ],
  },
  {
    number: 2,
    image: "/assets/soal-VZ/Soal 2.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/2. a.png" },
      { value: "b", image: "/assets/soal-VZ/2. b.png" },
      { value: "c", image: "/assets/soal-VZ/2. c.png" },
      { value: "d", image: "/assets/soal-VZ/2. d.png" },
      { value: "e", image: "/assets/soal-VZ/2. e.png" },
    ],
  },
  {
    number: 3,
    image: "/assets/soal-VZ/Soal 3.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/3. a.png" },
      { value: "b", image: "/assets/soal-VZ/3. b.png" },
      { value: "c", image: "/assets/soal-VZ/3.c.png" },
      { value: "d", image: "/assets/soal-VZ/3. d.png" },
      { value: "e", image: "/assets/soal-VZ/3. e.png" },
    ],
  },
  {
    number: 4,
    image: "/assets/soal-VZ/Soal 4.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/4. a.png" },
      { value: "b", image: "/assets/soal-VZ/4. b.png" },
      { value: "c", image: "/assets/soal-VZ/4. c.png" },
      { value: "d", image: "/assets/soal-VZ/4. d.png" },
      { value: "e", image: "/assets/soal-VZ/4. e.png" },
    ],
  },
  {
    number: 5,
    image: "/assets/soal-VZ/Soal 5.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/5 -A.png" },
      { value: "b", image: "/assets/soal-VZ/5 -B.png" },
      { value: "c", image: "/assets/soal-VZ/5 . c.png" },
      { value: "d", image: "/assets/soal-VZ/5 . d.png" },
      { value: "e", image: "/assets/soal-VZ/5 . e.png" },
    ],
  },
  {
    number: 6,
    image: "/assets/soal-VZ/Soal 6.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/6. a.png" },
      { value: "b", image: "/assets/soal-VZ/6. b.png" },
      { value: "c", image: "/assets/soal-VZ/6. c.png" },
      { value: "d", image: "/assets/soal-VZ/6. d.png" },
      { value: "e", image: "/assets/soal-VZ/6. e.png" },
    ],
  },
  {
    number: 7,
    image: "/assets/soal-VZ/Soal 7.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/7. a.png" },
      { value: "b", image: "/assets/soal-VZ/7. b.png" },
      { value: "c", image: "/assets/soal-VZ/7. c.png" },
      { value: "d", image: "/assets/soal-VZ/7. d.png" },
      { value: "e", image: "/assets/soal-VZ/7. e.png" },
    ],
  },
  {
    number: 8,
    image: "/assets/soal-VZ/Soal 8.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/8. a.png" },
      { value: "b", image: "/assets/soal-VZ/8. b.png" },
      { value: "c", image: "/assets/soal-VZ/8. c.png" },
      { value: "d", image: "/assets/soal-VZ/8. d.png" },
      { value: "e", image: "/assets/soal-VZ/8. e.png" },
    ],
  },
  {
    number: 9,
    image: "/assets/soal-VZ/Soal 9.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/9. a.png" },
      { value: "b", image: "/assets/soal-VZ/9. b.png" },
      { value: "c", image: "/assets/soal-VZ/9. c.png" },
      { value: "d", image: "/assets/soal-VZ/9. d.png" },
      { value: "e", image: "/assets/soal-VZ/9. e.png" },
    ],
  },
  {
    number: 10,
    image: "/assets/soal-VZ/Soal 10.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/10. a.png" },
      { value: "b", image: "/assets/soal-VZ/10. b.png" },
      { value: "c", image: "/assets/soal-VZ/10. c.png" },
      { value: "d", image: "/assets/soal-VZ/10. d.png" },
      { value: "e", image: "/assets/soal-VZ/10. e.png" },
    ],
  },
  {
    number: 11,
    image: "/assets/soal-VZ/Soal 11.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/11. a.png" },
      { value: "b", image: "/assets/soal-VZ/11. b.png" },
      { value: "c", image: "/assets/soal-VZ/11. c.png" },
      { value: "d", image: "/assets/soal-VZ/11. d.png" },
      { value: "e", image: "/assets/soal-VZ/11. e.png" },
    ],
  },
  {
    number: 12,
    image: "/assets/soal-VZ/Soal 12.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/12. a.png" },
      { value: "b", image: "/assets/soal-VZ/12. b.png" },
      { value: "c", image: "/assets/soal-VZ/12. c.png" },
      { value: "d", image: "/assets/soal-VZ/12. d.png" },
      { value: "e", image: "/assets/soal-VZ/12. e.png" },
    ],
  },
  {
    number: 13,
    image: "/assets/soal-VZ/Soal 13.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/13. a.png" },
      { value: "b", image: "/assets/soal-VZ/13. b.png" },
      { value: "c", image: "/assets/soal-VZ/13. c.png" },
      { value: "d", image: "/assets/soal-VZ/13. d.png" },
      { value: "e", image: "/assets/soal-VZ/13. e.png" },
    ],
  },
  {
    number: 14,
    image: "/assets/soal-VZ/Soal 14.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/14. a.png" },
      { value: "b", image: "/assets/soal-VZ/14. b.png" },
      { value: "c", image: "/assets/soal-VZ/14. c.png" },
      { value: "d", image: "/assets/soal-VZ/14. d.png" },
      { value: "e", image: "/assets/soal-VZ/14. e.png" },
    ],
  },
  {
    number: 15,
    image: "/assets/soal-VZ/Soal 15.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/15. a.png" },
      { value: "b", image: "/assets/soal-VZ/15. b.png" },
      { value: "c", image: "/assets/soal-VZ/15. c.png" },
      { value: "d", image: "/assets/soal-VZ/15. d.png" },
      { value: "e", image: "/assets/soal-VZ/15. e.png" },
    ],
  },
  {
    number: 16,
    image: "/assets/soal-VZ/Soal 16.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/16. a.png" },
      { value: "b", image: "/assets/soal-VZ/16. b.png" },
      { value: "c", image: "/assets/soal-VZ/16. c.png" },
      { value: "d", image: "/assets/soal-VZ/16. d.png" },
      { value: "e", image: "/assets/soal-VZ/16. e.png" },
    ],
  },
  {
    number: 17,
    image: "/assets/soal-VZ/Soal 17.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/17. a.png" },
      { value: "b", image: "/assets/soal-VZ/17. b.png" },
      { value: "c", image: "/assets/soal-VZ/17. c.png" },
      { value: "d", image: "/assets/soal-VZ/17. d.png" },
      { value: "e", image: "/assets/soal-VZ/17. e.png" },
    ],
  },
  {
    number: 18,
    image: "/assets/soal-VZ/Soal 18.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/18-A.png" },
      { value: "b", image: "/assets/soal-VZ/18-B.png" },
      { value: "c", image: "/assets/soal-VZ/18-C.png" },
      { value: "d", image: "/assets/soal-VZ/18-D.png" },
      { value: "e", image: "/assets/soal-VZ/18-E.png" },
    ],
  },
  {
    number: 19,
    image: "/assets/soal-VZ/Soal 19.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/19. a.png" },
      { value: "b", image: "/assets/soal-VZ/19. b.png" },
      { value: "c", image: "/assets/soal-VZ/19. c.png" },
      { value: "d", image: "/assets/soal-VZ/19. d.png" },
      { value: "e", image: "/assets/soal-VZ/19. e.png" },
    ],
  },
  {
    number: 20,
    image: "/assets/soal-VZ/Soal 20.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/20. a.png" },
      { value: "b", image: "/assets/soal-VZ/20. b.png" },
      { value: "c", image: "/assets/soal-VZ/20. c.png" },
      { value: "d", image: "/assets/soal-VZ/20. d.png" },
      { value: "e", image: "/assets/soal-VZ/20. e.png" },
    ],
  },
  {
    number: 21,
    image: "/assets/soal-VZ/Soal 21.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/21. a.png" },
      { value: "b", image: "/assets/soal-VZ/21. b.png" },
      { value: "c", image: "/assets/soal-VZ/21. c.png" },
      { value: "d", image: "/assets/soal-VZ/21. d.png" },
      { value: "e", image: "/assets/soal-VZ/21. e.png" },
    ],
  },
  {
    number: 22,
    image: "/assets/soal-VZ/Soal 22.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/22. a.png" },
      { value: "b", image: "/assets/soal-VZ/22. b.png" },
      { value: "c", image: "/assets/soal-VZ/22. c.png" },
      { value: "d", image: "/assets/soal-VZ/22. d.png" },
      { value: "e", image: "/assets/soal-VZ/22. e.png" },
    ],
  },
  {
    number: 23,
    image: "/assets/soal-VZ/Soal 23.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/23. a.png" },
      { value: "b", image: "/assets/soal-VZ/23. b.png" },
      { value: "c", image: "/assets/soal-VZ/23. c.png" },
      { value: "d", image: "/assets/soal-VZ/23. d.png" },
      { value: "e", image: "/assets/soal-VZ/23. e.png" },
    ],
  },
  {
    number: 24,
    image: "/assets/soal-VZ/Soal 24.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/24. a.png" },
      { value: "b", image: "/assets/soal-VZ/24. b.png" },
      { value: "c", image: "/assets/soal-VZ/24. c.png" },
      { value: "d", image: "/assets/soal-VZ/24. d.png" },
      { value: "e", image: "/assets/soal-VZ/24. e.png" },
    ],
  },
  {
    number: 25,
    image: "/assets/soal-VZ/Soal 25.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/25. a.png" },
      { value: "b", image: "/assets/soal-VZ/25. b.png" },
      { value: "c", image: "/assets/soal-VZ/25. c.png" },
      { value: "d", image: "/assets/soal-VZ/25. d.png" },
      { value: "e", image: "/assets/soal-VZ/25. e.png" },
    ],
  },
  {
    number: 26,
    image: "/assets/soal-VZ/Soal 26.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/26. a.png" },
      { value: "b", image: "/assets/soal-VZ/26. b.png" },
      { value: "c", image: "/assets/soal-VZ/26. c.png" },
      { value: "d", image: "/assets/soal-VZ/26. d.png" },
      { value: "e", image: "/assets/soal-VZ/26. e.png" },
    ],
  },
  {
    number: 27,
    image: "/assets/soal-VZ/Soal 27.png",
    options: [
      { value: "a", image: "/assets/soal-VZ/27. a.png" },
      { value: "b", image: "/assets/soal-VZ/27. b.png" },
      { value: "c", image: "/assets/soal-VZ/27. c.png" },
      { value: "d", image: "/assets/soal-VZ/27. d.png" },
      { value: "e", image: "/assets/soal-VZ/27. e.png" },
    ],
  },
];
