// Define questions with dynamic structure
export const imageData = [
  {
    number: 1,
    image: "/assets/soal-MV/SOAL 1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/1 - A.png" },
      { value: "b", image: "/assets/soal-MV/1 - B.png" },
      { value: "c", image: "/assets/soal-MV/1 - C.png" },
      { value: "d", image: "/assets/soal-MV/1 - D.png" },
      { value: "e", image: "/assets/soal-MV/1 - E.png" },
    ],
  },
  {
    number: 2,
    image: "/assets/soal-MV/SOAL 2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/2 - A.png" },
      { value: "b", image: "/assets/soal-MV/2 - B.png" },
      { value: "c", image: "/assets/soal-MV/2 - C.png" },
      { value: "d", image: "/assets/soal-MV/2 - D.png" },
      { value: "e", image: "/assets/soal-MV/2 - E.png" },
    ],
  },
  {
    number: 3,
    image: "/assets/soal-MV/SOAL 3.png",
    options: [
      { value: "a", image: "/assets/soal-MV/3 - A.png" },
      { value: "b", image: "/assets/soal-MV/3 - B.png" },
      { value: "c", image: "/assets/soal-MV/3 - C.png" },
      { value: "d", image: "/assets/soal-MV/3 - D.png" },
      { value: "e", image: "/assets/soal-MV/3 - E.png" },
    ],
  },
  {
    number: 4,
    image: "/assets/soal-MV/SOAL 4.png",
    options: [
      { value: "a", image: "/assets/soal-MV/4 - A.png" },
      { value: "b", image: "/assets/soal-MV/4 - B.png" },
      { value: "c", image: "/assets/soal-MV/4 - C.png" },
      { value: "d", image: "/assets/soal-MV/4 - D.png" },
      { value: "e", image: "/assets/soal-MV/4 - E.png" },
    ],
  },
  {
    number: 5,
    image: "/assets/soal-MV/SOAL 5.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/5.1 -A.png" },
      { value: "b", image: "/assets/soal-MV/5.1 -B.png" },
      { value: "c", image: "/assets/soal-MV/5.1  - C.png" },
      { value: "d", image: "/assets/soal-MV/5.1  - D.png" },
      { value: "e", image: "/assets/soal-MV/5.1  - E.png" },
    ],
  },
  {
    number: 6,
    image: "/assets/soal-MV/SOAL 5.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/5.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/5.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/5.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/5.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/5.2 - E.png" },
    ],
  },
  {
    number: 7,
    image: "/assets/soal-MV/SOAL 6.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/6.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/6.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/6.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/6.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/6.1 - E.png" },
    ],
  },
  {
    number: 8,
    image: "/assets/soal-MV/SOAL 6.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/6.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/6.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/6.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/6.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/6.2 - E.png" },
    ],
  },
  {
    number: 9,
    image: "/assets/soal-MV/SOAL 7.png",
    options: [
      { value: "a", image: "/assets/soal-MV/7 - A.png" },
      { value: "b", image: "/assets/soal-MV/7 - B.png" },
      { value: "c", image: "/assets/soal-MV/7 - C.png" },
      { value: "d", image: "/assets/soal-MV/7 - D.png" },
      { value: "e", image: "/assets/soal-MV/7 - E.png" },
    ],
  },
  {
    number: 10,
    image: "/assets/soal-MV/SOAL 8.png",
    options: [
      { value: "a", image: "/assets/soal-MV/8 - A.png" },
      { value: "b", image: "/assets/soal-MV/8 - B.png" },
      { value: "c", image: "/assets/soal-MV/8 - C.png" },
      { value: "d", image: "/assets/soal-MV/8 - D.png" },
      { value: "e", image: "/assets/soal-MV/8 - E.png" },
    ],
  },
  {
    number: 11,
    image: "/assets/soal-MV/SOAL 9.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/9.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/9.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/9.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/9.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/9.1 - E.png" },
    ],
  },
  {
    number: 12,
    image: "/assets/soal-MV/SOAL 9.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/9.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/9.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/9.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/9.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/9.2 - E.png" },
    ],
  },
  {
    number: 13,
    image: "/assets/soal-MV/SOAL 10.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/10.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/10.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/10.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/10.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/10.1 - E.png" },
    ],
  },
  {
    number: 14,
    image: "/assets/soal-MV/SOAL 10.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/10.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/10.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/10.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/10.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/10.2 - E.png" },
    ],
  },
  {
    number: 15,
    image: "/assets/soal-MV/SOAL 11.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/11.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/11.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/11.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/11.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/11.1 - E.png" },
    ],
  },
  {
    number: 16,
    image: "/assets/soal-MV/SOAL 11.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/11.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/11.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/11.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/11.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/11.2 - E.png" },
    ],
  },
  {
    number: 17,
    image: "/assets/soal-MV/SOAL 12.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/12.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/12.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/12.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/12.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/12.1 - E.png" },
    ],
  },
  {
    number: 18,
    image: "/assets/soal-MV/SOAL 12.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/12.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/12.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/12.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/12.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/12.2 - E.png" },
    ],
  },
  {
    number: 19,
    image: "/assets/soal-MV/SOAL 13.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/13.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/13.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/13.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/13.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/13.1 - E.png" },
    ],
  },
  {
    number: 20,
    image: "/assets/soal-MV/SOAL 13.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/13.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/13.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/13.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/13.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/13.2 - E.png" },
    ],
  },
  {
    number: 21,
    image: "/assets/soal-MV/SOAL 14.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/14.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/14.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/14.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/14.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/14.1 - E.png" },
    ],
  },
  {
    number: 22,
    image: "/assets/soal-MV/SOAL 14.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/14.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/14.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/14.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/14.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/14.2 - E.png" },
    ],
  },
  {
    number: 23,
    image: "/assets/soal-MV/SOAL 15.png",
    options: [
      { value: "a", image: "/assets/soal-MV/15 - A.png" },
      { value: "b", image: "/assets/soal-MV/15 - B.png" },
      { value: "c", image: "/assets/soal-MV/15 - C.png" },
      { value: "d", image: "/assets/soal-MV/15 - D.png" },
      { value: "e", image: "/assets/soal-MV/15 - E.png" },
    ],
  },
  {
    number: 24,
    image: "/assets/soal-MV/SOAL 16.png",
    options: [
      { value: "a", image: "/assets/soal-MV/16 - A.png" },
      { value: "b", image: "/assets/soal-MV/16 - B.png" },
      { value: "c", image: "/assets/soal-MV/16 - C.png" },
      { value: "d", image: "/assets/soal-MV/16 - D.png" },
      { value: "e", image: "/assets/soal-MV/16 - E.png" },
    ],
  },
  {
    number: 25,
    image: "/assets/soal-MV/SOAL 17.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/17.1 - A.png" },
      { value: "b", image: "/assets/soal-MV/17.1 - B.png" },
      { value: "c", image: "/assets/soal-MV/17.1 - C.png" },
      { value: "d", image: "/assets/soal-MV/17.1 - D.png" },
      { value: "e", image: "/assets/soal-MV/17.1 - E.png" },
    ],
  },
  {
    number: 26,
    image: "/assets/soal-MV/SOAL 17.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/17.2 - A.png" },
      { value: "b", image: "/assets/soal-MV/17.2 - B.png" },
      { value: "c", image: "/assets/soal-MV/17.2 - C.png" },
      { value: "d", image: "/assets/soal-MV/17.2 - D.png" },
      { value: "e", image: "/assets/soal-MV/17.2 - E.png" },
    ],
  },
  {
    number: 27,
    image: "/assets/soal-MV/SOAL 18.1.png",
    options: [
      { value: "a", image: "/assets/soal-MV/18.1-A.png" },
      { value: "b", image: "/assets/soal-MV/18.1-B.png" },
      { value: "c", image: "/assets/soal-MV/18.1-C.png" },
      { value: "d", image: "/assets/soal-MV/18.1-D.png" },
      { value: "e", image: "/assets/soal-MV/18.1-E.png" },
    ],
  },
  {
    number: 28,
    image: "/assets/soal-MV/SOAL 18.2.png",
    options: [
      { value: "a", image: "/assets/soal-MV/18.2-A.png" },
      { value: "b", image: "/assets/soal-MV/18.2-B.png" },
      { value: "c", image: "/assets/soal-MV/18.2-C.png" },
      { value: "d", image: "/assets/soal-MV/18.2-D.png" },
      { value: "e", image: "/assets/soal-MV/18.2-E.png" },
    ],
  },
  {
    number: 29,
    image: "/assets/soal-MV/SOAL 19.png",
    options: [
      { value: "a", image: "/assets/soal-MV/19 - A.png" },
      { value: "b", image: "/assets/soal-MV/19 - B.png" },
      { value: "c", image: "/assets/soal-MV/19 - C.png" },
      { value: "d", image: "/assets/soal-MV/19 - D.png" },
      { value: "e", image: "/assets/soal-MV/19 - E.png" },
    ],
  },
  {
    number: 30,
    image: "/assets/soal-MV/SOAL 20.png",
    options: [
      { value: "a", image: "/assets/soal-MV/20 - A.png" },
      { value: "b", image: "/assets/soal-MV/20 - B.png" },
      { value: "c", image: "/assets/soal-MV/20 - C.png" },
      { value: "d", image: "/assets/soal-MV/20 - D.png" },
      { value: "e", image: "/assets/soal-MV/20 - E.png" },
    ],
  },
];
