// Define questions with dynamic structure
export const imageData = [
  {
    number: 1,
    image: "/assets/soal-GFI/Soal 1.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/1. a.png" },
      { value: "b", image: "/assets/soal-GFI/1. b.png" },
      { value: "c", image: "/assets/soal-GFI/1. c.png" },
      { value: "d", image: "/assets/soal-GFI/1. d.png" },
      { value: "e", image: "/assets/soal-GFI/1. e.png" },
    ],
  },
  {
    number: 2,
    image: "/assets/soal-GFI/Soal 2.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/2. a.png" },
      { value: "b", image: "/assets/soal-GFI/2. b.png" },
      { value: "c", image: "/assets/soal-GFI/2. c.png" },
      { value: "d", image: "/assets/soal-GFI/2. d.png" },
      { value: "e", image: "/assets/soal-GFI/2. e.png" },
    ],
  },
  {
    number: 3,
    image: "/assets/soal-GFI/Soal 3.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/3. a.png" },
      { value: "b", image: "/assets/soal-GFI/3. b.png" },
      { value: "c", image: "/assets/soal-GFI/3. c.png" },
      { value: "d", image: "/assets/soal-GFI/3. d.png" },
      { value: "e", image: "/assets/soal-GFI/3. e.png" },
    ],
  },
  {
    number: 4,
    image: "/assets/soal-GFI/Soal 4.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/4. a.png" },
      { value: "b", image: "/assets/soal-GFI/4. b.png" },
      { value: "c", image: "/assets/soal-GFI/4. c.png" },
      { value: "d", image: "/assets/soal-GFI/4. d.png" },
      { value: "e", image: "/assets/soal-GFI/4. e.png" },
    ],
  },
  {
    number: 5,
    image: "/assets/soal-GFI/Soal 5.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/5. a.png" },
      { value: "b", image: "/assets/soal-GFI/5. b.png" },
      { value: "c", image: "/assets/soal-GFI/5. c.png" },
      { value: "d", image: "/assets/soal-GFI/5. d.png" },
      { value: "e", image: "/assets/soal-GFI/5. e.png" },
    ],
  },
  {
    number: 6,
    image: "/assets/soal-GFI/Soal 6.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/6. a.png" },
      { value: "b", image: "/assets/soal-GFI/6. b.png" },
      { value: "c", image: "/assets/soal-GFI/6. c.png" },
      { value: "d", image: "/assets/soal-GFI/6. d.png" },
      { value: "e", image: "/assets/soal-GFI/6. e.png" },
    ],
  },
  {
    number: 7,
    image: "/assets/soal-GFI/Soal 7.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/7. a.png" },
      { value: "b", image: "/assets/soal-GFI/7. b.png" },
      { value: "c", image: "/assets/soal-GFI/7. c.png" },
      { value: "d", image: "/assets/soal-GFI/7. d.png" },
      { value: "e", image: "/assets/soal-GFI/7. e.png" },
    ],
  },
  {
    number: 8,
    image: "/assets/soal-GFI/Soal 8.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/8. a.png" },
      { value: "b", image: "/assets/soal-GFI/8. b.png" },
      { value: "c", image: "/assets/soal-GFI/8. c.png" },
      { value: "d", image: "/assets/soal-GFI/8. d.png" },
      { value: "e", image: "/assets/soal-GFI/8. e.png" },
    ],
  },
  {
    number: 9,
    image: "/assets/soal-GFI/Soal 9.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/9. a.png" },
      { value: "b", image: "/assets/soal-GFI/9. b.png" },
      { value: "c", image: "/assets/soal-GFI/9. c.png" },
      { value: "d", image: "/assets/soal-GFI/9. d.png" },
      { value: "e", image: "/assets/soal-GFI/9. e.png" },
    ],
  },
  {
    number: 10,
    image: "/assets/soal-GFI/Soal 10.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/10. a.png" },
      { value: "b", image: "/assets/soal-GFI/10. b.png" },
      { value: "c", image: "/assets/soal-GFI/10. c.png" },
      { value: "d", image: "/assets/soal-GFI/10. d.png" },
      { value: "e", image: "/assets/soal-GFI/10. e.png" },
    ],
  },
  {
    number: 11,
    image: "/assets/soal-GFI/Soal 11.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/11. a.png" },
      { value: "b", image: "/assets/soal-GFI/11. b.png" },
      { value: "c", image: "/assets/soal-GFI/11. c.png" },
      { value: "d", image: "/assets/soal-GFI/11. d.png" },
      { value: "e", image: "/assets/soal-GFI/11. e.png" },
    ],
  },
  {
    number: 12,
    image: "/assets/soal-GFI/Soal 12.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/12. a.png" },
      { value: "b", image: "/assets/soal-GFI/12. b.png" },
      { value: "c", image: "/assets/soal-GFI/12. c.png" },
      { value: "d", image: "/assets/soal-GFI/12. d.png" },
      { value: "e", image: "/assets/soal-GFI/12. e.png" },
    ],
  },
  {
    number: 13,
    image: "/assets/soal-GFI/Soal 13.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/13. a.png" },
      { value: "b", image: "/assets/soal-GFI/13. b.png" },
      { value: "c", image: "/assets/soal-GFI/13. c.png" },
      { value: "d", image: "/assets/soal-GFI/13. d.png" },
      { value: "e", image: "/assets/soal-GFI/13. e.png" },
    ],
  },
  {
    number: 14,
    image: "/assets/soal-GFI/Soal 14.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/14. a.png" },
      { value: "b", image: "/assets/soal-GFI/14. b.png" },
      { value: "c", image: "/assets/soal-GFI/14. c.png" },
      { value: "d", image: "/assets/soal-GFI/14. d.png" },
      { value: "e", image: "/assets/soal-GFI/14. e.png" },
    ],
  },
  {
    number: 15,
    image: "/assets/soal-GFI/Soal 15.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/15. a.png" },
      { value: "b", image: "/assets/soal-GFI/15. b.png" },
      { value: "c", image: "/assets/soal-GFI/15. c.png" },
      { value: "d", image: "/assets/soal-GFI/15. d.png" },
      { value: "e", image: "/assets/soal-GFI/15. e.png" },
    ],
  },
  {
    number: 16,
    image: "/assets/soal-GFI/Soal 16.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/16. a.png" },
      { value: "b", image: "/assets/soal-GFI/16. b.png" },
      { value: "c", image: "/assets/soal-GFI/16. c.png" },
      { value: "d", image: "/assets/soal-GFI/16. d.png" },
      { value: "e", image: "/assets/soal-GFI/16. e.png" },
    ],
  },
  {
    number: 17,
    image: "/assets/soal-GFI/Soal 17.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/17. a.png" },
      { value: "b", image: "/assets/soal-GFI/17. b.png" },
      { value: "c", image: "/assets/soal-GFI/17. c.png" },
      { value: "d", image: "/assets/soal-GFI/17. d.png" },
      { value: "e", image: "/assets/soal-GFI/17. e.png" },
    ],
  },
  {
    number: 18,
    image: "/assets/soal-GFI/Soal 18.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/18. a.png" },
      { value: "b", image: "/assets/soal-GFI/18. b.png" },
      { value: "c", image: "/assets/soal-GFI/18. c.png" },
      { value: "d", image: "/assets/soal-GFI/18. d.png" },
      { value: "e", image: "/assets/soal-GFI/18. e.png" },
    ],
  },
  {
    number: 19,
    image: "/assets/soal-GFI/Soal 19.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/19. a.png" },
      { value: "b", image: "/assets/soal-GFI/19. b.png" },
      { value: "c", image: "/assets/soal-GFI/19. c.png" },
      { value: "d", image: "/assets/soal-GFI/19. d.png" },
      { value: "e", image: "/assets/soal-GFI/19. e.png" },
    ],
  },
  {
    number: 20,
    image: "/assets/soal-GFI/Soal 20.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/20. a.png" },
      { value: "b", image: "/assets/soal-GFI/20. b.png" },
      { value: "c", image: "/assets/soal-GFI/20. c.png" },
      { value: "d", image: "/assets/soal-GFI/20. d.png" },
      { value: "e", image: "/assets/soal-GFI/20. e.png" },
    ],
  },
  {
    number: 21,
    image: "/assets/soal-GFI/Soal 21.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/21. a.png" },
      { value: "b", image: "/assets/soal-GFI/21. b.png" },
      { value: "c", image: "/assets/soal-GFI/21. c.png" },
      { value: "d", image: "/assets/soal-GFI/21. d.png" },
      { value: "e", image: "/assets/soal-GFI/21. e.png" },
    ],
  },
  {
    number: 22,
    image: "/assets/soal-GFI/Soal 22.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/22. a.png" },
      { value: "b", image: "/assets/soal-GFI/22. b.png" },
      { value: "c", image: "/assets/soal-GFI/22. c.png" },
      { value: "d", image: "/assets/soal-GFI/22. d.png" },
      { value: "e", image: "/assets/soal-GFI/22. e.png" },
    ],
  },
  {
    number: 23,
    image: "/assets/soal-GFI/Soal 23.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/23. a.png" },
      { value: "b", image: "/assets/soal-GFI/23. b.png" },
      { value: "c", image: "/assets/soal-GFI/23. c.png" },
      { value: "d", image: "/assets/soal-GFI/23. d.png" },
      { value: "e", image: "/assets/soal-GFI/23. e.png" },
    ],
  },
  {
    number: 24,
    image: "/assets/soal-GFI/Soal 24.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/24. a.png" },
      { value: "b", image: "/assets/soal-GFI/24. b.png" },
      { value: "c", image: "/assets/soal-GFI/24. c.png" },
      { value: "d", image: "/assets/soal-GFI/24. d.png" },
      { value: "e", image: "/assets/soal-GFI/24. e.png" },
    ],
  },
  {
    number: 25,
    image: "/assets/soal-GFI/Soal 25.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/25. a.png" },
      { value: "b", image: "/assets/soal-GFI/25. b.png" },
      { value: "c", image: "/assets/soal-GFI/25. c.png" },
      { value: "d", image: "/assets/soal-GFI/25. d.png" },
      { value: "e", image: "/assets/soal-GFI/25. e.png" },
    ],
  },
  {
    number: 26,
    image: "/assets/soal-GFI/Soal 26.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/26. a.png" },
      { value: "b", image: "/assets/soal-GFI/26. b.png" },
      { value: "c", image: "/assets/soal-GFI/26. c.png" },
      { value: "d", image: "/assets/soal-GFI/26. d.png" },
      { value: "e", image: "/assets/soal-GFI/26. e.png" },
    ],
  },
  {
    number: 27,
    image: "/assets/soal-GFI/Soal 27.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/27. a.png" },
      { value: "b", image: "/assets/soal-GFI/27. b.png" },
      { value: "c", image: "/assets/soal-GFI/27. c.png" },
      { value: "d", image: "/assets/soal-GFI/27. d.png" },
      { value: "e", image: "/assets/soal-GFI/27. e.png" },
    ],
  },
  {
    number: 28,
    image: "/assets/soal-GFI/Soal 28.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/28. a.png" },
      { value: "b", image: "/assets/soal-GFI/28. b.png" },
      { value: "c", image: "/assets/soal-GFI/28. c.png" },
      { value: "d", image: "/assets/soal-GFI/28. d.png" },
      { value: "e", image: "/assets/soal-GFI/28. e.png" },
    ],
  },
  {
    number: 29,
    image: "/assets/soal-GFI/Soal 29.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/29. a.png" },
      { value: "b", image: "/assets/soal-GFI/29. b.png" },
      { value: "c", image: "/assets/soal-GFI/29. c.png" },
      { value: "d", image: "/assets/soal-GFI/29. d.png" },
      { value: "e", image: "/assets/soal-GFI/29. e.png" },
    ],
  },
  {
    number: 30,
    image: "/assets/soal-GFI/Soal 30.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/30. a.png" },
      { value: "b", image: "/assets/soal-GFI/30. b.png" },
      { value: "c", image: "/assets/soal-GFI/30. c.png" },
      { value: "d", image: "/assets/soal-GFI/30. d.png" },
      { value: "e", image: "/assets/soal-GFI/30. e.png" },
    ],
  },
  {
    number: 31,
    image: "/assets/soal-GFI/Soal 31.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/31. a.png" },
      { value: "b", image: "/assets/soal-GFI/31. b.png" },
      { value: "c", image: "/assets/soal-GFI/31. c.png" },
      { value: "d", image: "/assets/soal-GFI/31. d.png" },
      { value: "e", image: "/assets/soal-GFI/31. e.png" },
    ],
  },
  {
    number: 32,
    image: "/assets/soal-GFI/Soal 32.png",
    options: [
      { value: "a", image: "/assets/soal-GFI/32. a.png" },
      { value: "b", image: "/assets/soal-GFI/32. b.png" },
      { value: "c", image: "/assets/soal-GFI/32. c.png" },
      { value: "d", image: "/assets/soal-GFI/32. d.png" },
      { value: "e", image: "/assets/soal-GFI/32. e.png" },
    ],
  },
];
