export const questionsData = [
  {
    questions: [
      {
        number: 1,
        text: " 2, 5, 8, 11, 14, ___, 20",
        options: [
          { value: "a", text: "15" },
          { value: "b", text: "16" },
          { value: "c", text: "17" },
          { value: "d", text: "18" },
          { value: "e", text: "19" },
        ],
      },
      {
        number: 2,
        text: "20, 18, 16, 14, 12, ___, 8",
        options: [
          { value: "a", text: "13" },
          { value: "b", text: "12" },
          { value: "c", text: "11" },
          { value: "d", text: "10" },
          { value: "e", text: "9" },
        ],
      },
      {
        number: 3,
        text: " 2, 4, 8, 16, 32, ___, 128",
        options: [
          { value: "a", text: "48" },
          { value: "b", text: "56" },
          { value: "c", text: "64" },
          { value: "d", text: "80" },
          { value: "e", text: "96" },
        ],
      },
      {
        number: 4,
        text: "486, 162, 54, 18, 6, ___, ⅔",
        options: [
          { value: "a", text: "5" },
          { value: "b", text: "4" },
          { value: "c", text: "3" },
          { value: "d", text: "2" },
          { value: "e", text: "1" },
        ],
      },
      {
        number: 5,
        text: "1, 1, 2, 3, 5, ___, 13",
        options: [
          { value: "a", text: "7" },
          { value: "b", text: "8" },
          { value: "c", text: "9" },
          { value: "d", text: "10" },
          { value: "e", text: "11" },
        ],
      },
      {
        number: 6,
        text: "1, 2, 6, 24, 120, ___, 5040",
        options: [
          { value: "a", text: "240" },
          { value: "b", text: "360" },
          { value: "c", text: "600" },
          { value: "d", text: "720" },
          { value: "e", text: "3125" },
        ],
      },
      {
        number: 7,
        text: "1, 4, 9, 16, 25, ___, 49",
        options: [
          { value: "a", text: "30" },
          { value: "b", text: "32" },
          { value: "c", text: "36" },
          { value: "d", text: "40" },
          { value: "e", text: "45" },
        ],
      },
      {
        number: 8,
        text: "1, 8, 27, 64, 125, ___, 343",
        options: [
          { value: "a", text: "169" },
          { value: "b", text: "216" },
          { value: "c", text: "250" },
          { value: "d", text: "289" },
          { value: "e", text: "324" },
        ],
      },
      {
        number: 9,
        text: "21, 34, 55, 89, 144, ___, 377",
        options: [
          { value: "a", text: "169" },
          { value: "b", text: "212" },
          { value: "c", text: "233" },
          { value: "d", text: "288" },
          { value: "e", text: "333" },
        ],
      },
      {
        number: 10,
        text: "10, 15, 12, 17, 14, 19, ___, 21",
        options: [
          { value: "a", text: "20" },
          { value: "b", text: "19" },
          { value: "c", text: "17" },
          { value: "d", text: "16" },
          { value: "e", text: "15" },
        ],
      },
      {
        number: 11,
        text: " 3, 6, 9, 7, 10, 13, ___, 14",
        options: [
          { value: "a", text: "7" },
          { value: "b", text: "8" },
          { value: "c", text: "9" },
          { value: "d", text: "10" },
          { value: "e", text: "11" },
        ],
      },
      {
        number: 12,
        text: "2, 4, 8, 10, 20, 22, ___, 46",
        options: [
          { value: "a", text: "24" },
          { value: "b", text: "32" },
          { value: "c", text: "34" },
          { value: "d", text: "42" },
          { value: "e", text: "44" },
        ],
      },
      {
        number: 13,
        text: "2032, 4, 1016, 8, 508, 24, 254, 96, ___",
        options: [
          { value: "a", text: "48" },
          { value: "b", text: "72" },
          { value: "c", text: "96" },
          { value: "d", text: "127" },
          { value: "e", text: "132" },
        ],
      },
      {
        number: 14,
        text: "28, 7, 9, 27, 8, 11, 26, 9, ___",
        options: [
          { value: "a", text: "10" },
          { value: "b", text: "13" },
          { value: "c", text: "18" },
          { value: "d", text: "25" },
          { value: "e", text: "28" },
        ],
      },
      {
        number: 15,
        text: "1, 7, 3, 13, 19, 3, ___, 31",
        options: [
          { value: "a", text: "3" },
          { value: "b", text: "11" },
          { value: "c", text: "27" },
          { value: "d", text: "25" },
          { value: "e", text: "29" },
        ],
      },
      {
        number: 16,
        text: "8, 9, 12, 17, 24, 33, 44, ___, 72",
        options: [
          { value: "a", text: "57" },
          { value: "b", text: "56" },
          { value: "c", text: "54" },
          { value: "d", text: "55" },
          { value: "e", text: "53" },
        ],
      },
      {
        number: 17,
        text: "1, 11, 3, 10, 5, 9, 7, ___, 9 ",
        options: [
          { value: "a", text: "11" },
          { value: "b", text: "10" },
          { value: "c", text: "9" },
          { value: "d", text: "8" },
          { value: "e", text: "7" },
        ],
      },
      {
        number: 18,
        text: "1/2, 1/4, 5/6, 1/2, 7/6, 3/4, ___, 1",
        options: [
          { value: "a", text: "9/8" },
          { value: "b", text: "8/9" },
          { value: "c", text: "8/6" },
          { value: "d", text: "6/9" },
          { value: "e", text: "9/6" },
        ],
      },
      {
        number: 19,
        text: "15, 6, 45, 36, 75, 216, 105, ___, 135",
        options: [
          { value: "a", text: "125" },
          { value: "b", text: "225" },
          { value: "c", text: "866" },
          { value: "d", text: "1080" },
          { value: "e", text: "1296" },
        ],
      },
      {
        number: 20,
        text: "2, 4, 6, 16, 14, 80, 26, ___, 42",
        options: [
          { value: "a", text: "40" },
          { value: "b", text: "112" },
          { value: "c", text: "240" },
          { value: "d", text: "324" },
          { value: "e", text: "480" },
        ],
      },
      {
        number: 21,
        text: "12, 29, 63, 131, 267, __, 1083",
        options: [
          { value: "a", text: "398" },
          { value: "b", text: "461" },
          { value: "c", text: "539" },
          { value: "d", text: "738" },
          { value: "e", text: "801" },
        ],
      },
      {
        number: 22,
        text: "1, 3, 7, 15, 31, 63, 127, __, 511",
        options: [
          { value: "a", text: "240" },
          { value: "b", text: "248" },
          { value: "c", text: "252" },
          { value: "d", text: "255" },
          { value: "e", text: "260" },
        ],
      },
      {
        number: 23,
        text: "850, 812, 800, 808, 750, 792, 700, __, 650",
        options: [
          { value: "a", text: "728" },
          { value: "b", text: "725" },
          { value: "c", text: "712" },
          { value: "d", text: "690" },
          { value: "e", text: "675" },
        ],
      },
      {
        number: 24,
        text: "2, 3, 4, 5, 8, 7, 16, 9, __, 11",
        options: [
          { value: "a", text: "10" },
          { value: "b", text: "25" },
          { value: "c", text: "28" },
          { value: "d", text: "32" },
          { value: "e", text: "36" },
        ],
      },
      {
        number: 25,
        text: "15, 30, 62, 128, 262, 532, 1074, __, 4334",
        options: [
          { value: "a", text: "2100" },
          { value: "b", text: "2121" },
          { value: "c", text: "2140" },
          { value: "d", text: "2160" },
          { value: "e", text: "2222" },
        ],
      },
    ],
  },
];
